### ISSUE TITLE
YearView makes Reminder overlay icons disappear

### ISSUE THREAD

**Issue by hagen5** [fabrixxm/Year-View#27] opened 2019-06-17 06:42 UTC
Hello,
Window 10 Home 64bit, Version 1803 (OS Build 17134.829)
Thunderbird  60.7.1 (32-bit)
Lightning (built into TB) 6.2.7.1
YearView 0.6.1

If YearView is enabled, all the reminder overlay *icons* disappear (little bell in upper right corner of events for which a reminder is set, see pic.s), in the day, week, multi week and month views.  
It is thus not possible to see if a reminder has been set or not for an event. 

This seems to be a GUI/icon issue only: the reminders themselves still work OK.
Just _disabling_ (not removing) YearView will "fix" this and bring those icons back.

In earlier versions of YearView, TB, and Lightning (under Win7), this problem was not observed.

This seems to be the same issue (now closed) which has earlier been [reported for Ubuntu](https://github.com/fabrixxm/Year-View/issues/24) already.

Cheers.

with YearView **en**abled:
![YearView_Enabled](https://user-images.githubusercontent.com/25004791/59582923-6996a600-90e2-11e9-894e-06765e8e51a9.png)

with YearView **dis**abled:
![YearView_Disabled](https://user-images.githubusercontent.com/25004791/59582933-70251d80-90e2-11e9-8662-554c476e30d2.png)

**Comment by fabrixxm** [comment] 2019-06-17 07:34
I'm closing this as is a duplicate of #24 , which has been fixed in code.
Release with fix is pending

**Closed by fabrixxm** 2019-06-17 07:34 UTC
